name: S3 Deploy Website

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
  
      - name: Checkout Scripts
        uses: actions/checkout@v2
        with:
          path: tools
          repository: Bancar/uala-scripts-actions
          token: ${{ secrets.UALA_GLOBAL_GITHUB_TOKEN }}

      - name: Setup AWS Credentials
        run: sh setup-credentials-ops-arg.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        working-directory: tools/scripts

      - name: 'Setup AWS Credentials Profile to Assume Role'
        run: |
          echo "[uala-mex-websites-prod]" >> ~/.aws/credentials
          echo "role_arn = $AWS_IAM_GITHUB_ACTIONS_ROLE_ARN_PROD" >> ~/.aws/credentials
          echo "source_profile = uala-operaciones" >> ~/.aws/credentials
          echo "[profile uala-mex-websites-prod]" > ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
        env:
          AWS_IAM_GITHUB_ACTIONS_ROLE_ARN_PROD: ${{ secrets.AWS_IAM_GITHUB_ACTIONS_ROLE_ARN_PROD }}
        working-directory: tools/scripts         

      - name: S3 Bucket Sync
        run: aws s3 sync . s3://uala-mex-frontend-websites-prod --profile uala-mex-websites-prod --exclude ".git*"
  
      - name: CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id E1IWGYZ0Q6KTK7 --paths "/*" --profile uala-mex-websites-prod
      
      # - name: Send Slack Message
      #   run: python3 slack.py
      #   env:
      #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #       ACTION_STATUS: ${{ job.status }}
      #   working-directory: .github/actions/uala-ftp-deploy-action
      